DROP TABLE IF EXISTS `post`;
CREATE TABLE IF NOT EXISTS `post` (
 `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
 `title` VARCHAR(255) NOT NULL,
 `text` TEXT NOT NULL,
 PRIMARY KEY  (`id`)
);

DROP TABLE IF EXISTS `comment`;
CREATE TABLE IF NOT EXISTS `comment` (
 `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
 `text` TEXT NOT NULL,
 `post_id` INT(10) UNSIGNED NOT NULL,
 PRIMARY KEY  (`id`)
);